#!/bin/bash
#Production version

#$1 is PSF sub_dir  Ex: V330 or V190
#$2 Zn_AZ and threshold specification EX: 20Deg50mv  (if az=0) or 20_180Deg50mv
#$3 Output file BaseName Ex: WMDL2  WMDL15A etc. First letter will be atm spec in newer KASCADEs
#$4 Input Sub-dir: Ex: ABCD
#$5 PMT type: W or V or U  Defaults to V

lcl=$PWD
echo PSF Sub_dir: $1
echo ZN_AzThreshold: $2
Base=$3
echo Base: $Base
echo SubDir: $4

if test -z $4 ;
then
 echo Fatal-Please supply all arguments Ex: ./Process V190 20Deg50mv SMDL15 wxyz
 exit
fi

##################################################################
#For use with Upgrade allow for PMT type specification defualts to Veritas (V)
###################################################################
if test -z $5 ;
then
  PMT='V'
else
  PMT=$5
fi


#####################################################################
# For compatability with the old version sof VEGAS where the
#  is given  the form:  U190MDL6 ("U" for US76 atm)
# Remove the first letter for filenames (will be atm spec in newer KASCADEs)
#####################################################################
ABase=${Base:0:1}

PBase=$ABase$PMT'P'$2
echo PBase: $PBase
PDir=$PBase'1234M2'$3 
echo PDir: $PDir
PDirOrig=$PBase'1234M2'$ABase$4 
echo PDirOrig: $PDirOrig


He4Base=$ABase$PMT'He4_'$2
echo He4Base: $He4Base
He4Dir=$He4Base'1234M2'$3
echo He4Dir: $He4Dir
He4DirOrig=$He4Base'1234M2'$ABase$4 
echo He4DirOrig: $He4DirOrig



#################Find protons first ##################
cd $lcl'/protons/'   #Find our input directory and put it in the right place
pwd                     # with the right name.
if [ -d "$PDirOrig" ]; then
   mkdir -vp $PDir
   cd $PDirOrig
   pwd
   mv -v *.vbf  $lcl'/protons/'$PDir'/'
fi


########## Now He4 #################
cd $lcl'/he4/'    #Find our input directory and put it in the right place
pwd                     # with the right name.
if [ -d "$He4DirOrig" ]; then
  mkdir -vp $He4Dir
  cd $He4DirOrig  
  mv -v *.vbf  $lcl'/he4/'$He4Dir'/'
fi

VBFFile=$3$PMT'CR'$2'1234M2.vbf'
echo Output File Name: $VBFFile

cd $lcl'/../../veritas'

sgeFile=$lcl'/'$3$PMT'CR'$2'.pbs'
echo "#"!/bin/bash                                       >$sgeFile
echo "#"PBS -l walltime=05:00:00                        >>$sgeFile
echo cd $lcl'/../../veritas'                            >>$sgeFile
echo './ksWeRock.scr W'$PMT'CR'$2 98020 1234M2 -1 $3 \\ >>$sgeFile
echo ">"$lcl/'/'$3$PMT'CR'$2'.log'                          >>$sgeFile
echo cd $lcl                                            >>$sgeFile
echo mv  -v 'W'$PMT'CR'$2'1234M2'$3'.vbf' $VBFFile      >>$sgeFile
echo ./ksVegasSimProduction.scr $VBFFile \\             >>$sgeFile
echo ">"$lcl'/'$VBFFile'.log'                           >>$sgeFile
#echo cd $lcl'/protons'                                 >>$sgeFile
#echo mv $PDir './'$1'/'$PDir                           >>$sgeFile
#echo cd  $lcl'/he4'                                    >>$sgeFile
#echo mv $He4Dir './'$1'/'$He4Dir                       >>$sgeFile

chmod 700 $sgeFile

qsub -q serial -V -e $sgeFile'.err' -o $sgeFile'.log' $sgeFile 


