#!/bin/bash
#This is a generic process list of Job files. It submits exixting jobs files
#$1 List of Job files to submit
host=$(hostname)
echo host: $host
hostString=${host:0:4}

if test  "$hostString" = "cori"  #Are we running on Cori
then
  QUEUE=serial
fi

hostString=${host:0:4}
if test  "$hostString" = "bell"  #Are we running on Bell
then
  QUEUE1=physics
  QUEUE2=standby
  QUEUE=$QUEUE1
fi

{
  while read InputJob ; do
      qsub -q $QUEUE  -V -e $InputJob'.err' -o $InputJob'.log' $InputJob
  done
} <$1
